### ISSUE TITLE
Config Editing

### ISSUE THREAD

**Issue by MythicGhoul** [kicjow/Crazy-Envoy#11]
Things i change on the config,

Random Location to True
Max Distance to 200
Time of day to '5:ooPM'
minimum players to 2
Max crate toggle to true
Max crates to 15

Everytime i chagne these in the config i /envoy reload and tried restarting the server, i then use /envoy start but all i get is An Internal Error Occured While Attempting This Command.

Any Fixes???

Thanks

**Comment by kicjow** [comment]
Please pastebin the config and the error.

**Comment by MythicGhoul** [comment]
http://pastebin.com/7vbzMHb1

Here You Go

**Comment by MythicGhoul** [comment]
completely forget anything i have said.. i litterally just found the /envoy center command.. i feel real dumb.. xD allow me to change my review

**Comment by kicjow** [comment]
Lol, its alright.
