### ISSUE TITLE
Sending 10m message twice

### ISSUE THREAD

**Issue by ghost** [kicjow/Crazy-Envoy#12]
http://i.imgur.com/WIbFj7W.png

Nothing interesting in console.

**Comment by kicjow** [comment]
Strange, pastebin your config please.

**Comment by ThatGamerBlue** [comment]
https://pastebin.com/3n5U9s8Q

**Comment by ThatGamerBlue** [comment]
Nope, seems random.

**Comment by kicjow** [comment]
Weird, I haven't seen it happen on my test server. I'll try again and see if it happens but just try a reload or restart and it might fix it.

**Comment by ThatGamerBlue** [comment]
Forgot to mention on my old account, this can be closed now, not sure how I fixed it but I think it was fixed by removing all the plugins then adding them back in.
