### ISSUE TITLE
Can not support a variety of worlds

### ISSUE THREAD

**Issue by z123x894** [kicjow/Crazy-Envoy#14]
example:
I need this plugin to work in a world (world name: Envoy)
But he can only specify a world
Can not support multiple worlds (Multiverse)
----------------------------------------------------------------------
He can only support the broadcast in other worlds
   World-Messages:
     Toggle: true
     Worlds:
       - 's1'

Crazy Envoy spawn support less than the rest of the world
-----------------------------------------------------------------
data.yml
Center: s1:s1, X:0, Y:0, Z:0
Locations:
  Spawns: []
Next-Envoy:

**Comment by kicjow** [comment]
Still not sure on what you mean. Can you specify where you want to see multi-world support?

**Comment by z123x894** [comment]
Yes, he can not work outside the world of "world"
my English is not very good

**Comment by z123x894** [comment]
That can be added to support other worlds?

**Comment by kicjow** [comment]
I figured you didn't know English very well since you keep saying "he". Its fine thought but could to point out what part of the file you mean.

**Comment by z123x894** [comment]
I am sorry, English is not very good! Make you feel

I mean "he" is another world

**Comment by z123x894** [comment]
Https://www.spigotmc.org/resources/multiverse-core.390/
Multiverse is able to produce a world
But I produced the s1 world
Crazy Envoy can not work in s1 world
Broadcast can be
Produce box can not

**Comment by kicjow** [comment]
Wait, why do you have it like this.
Center: s1:s1, X:0, Y:0, Z:0
It should be this.
Center: World:s1, X:0, Y:0, Z:0

**Comment by z123x894** [comment]
Thank you, the problem is solved
I admire you as a teacher
