### ISSUE TITLE
Chances Not Working

### ISSUE THREAD

**Issue by PrimeMoose** [kicjow/Crazy-Envoy#19]
[https://pastebin.com/3LtCz5DY](url)  <--- This is my config if you see something wrong tell me but on the Jester Rank when I start a envoy the chance is not 1 to 100 it is more like 1 to 5 so if you could help me I would really like that thank you love the plugin.

**Comment by kicjow** [comment]
Its probably because you only have a few prizes but it shouldn't be that common. If you need just make duplicates of some prizes and it will raise the chance of that and lower the chance of the prize you want less of.

**Comment by kicjow** [comment]
@PrimeMoose was something wrong with what I said? I saw you gave me unhappy reactions.
